from enum import Enum

class GenreEnum(Enum):
    ALTERNATIVE = 'Alternative'
    BLUES = 'Blues'
    CLASSICAL = 'Classical'
    COUNTRY = 'Country'
    ELECTRONIC = 'Electronic'
    FOLK = 'Folk'
    FUNK = 'Funk'
    HIPHOP = 'Hip-Hop'
    HEAVYMETAL = 'Heavy Metal'
    INSTRUMENTAL = 'Instrumental'
    JAZZ = 'Jazz'
    MUSICALTHEATRE = 'Musical Theatre'
    POP = 'Pop'
    PUNK = 'Punk'
    RB = 'R&B'
    REGGAE = 'Reggae'
    ROCKNROLL = 'Rock n Roll'
    SOUL = 'Soul'
    OTHER = 'Other'